









//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewProjectionSample.DomainModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksEntities : DbContext
    {
        public AdventureWorksEntities() : base("name=AdventureWorksEntities")
        {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductDescription> ProductDescriptions { get; set; }
        public DbSet<ProductModel> ProductModels { get; set; }
        public DbSet<ProductModelProductDescription> ProductModelProductDescriptions { get; set; }
        public DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
        
        private static bool _isInitialized;
        
        public static void Initialize()
        {
            if (!_isInitialized)
            {
                _isInitialized = true;
                ViewProjectionSample.DomainModels.Address._Initialize();
                ViewProjectionSample.DomainModels.Customer._Initialize();
                ViewProjectionSample.DomainModels.CustomerAddress._Initialize();
                ViewProjectionSample.DomainModels.Product._Initialize();
                ViewProjectionSample.DomainModels.ProductCategory._Initialize();
                ViewProjectionSample.DomainModels.ProductDescription._Initialize();
                ViewProjectionSample.DomainModels.ProductModel._Initialize();
                ViewProjectionSample.DomainModels.ProductModelProductDescription._Initialize();
                ViewProjectionSample.DomainModels.SalesOrderDetail._Initialize();
                ViewProjectionSample.DomainModels.SalesOrderHeader._Initialize();
            }
        }
    }
}
