

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Intersoft.AppFramework.ModelServices;
using Intersoft.Crosslight;
using Intersoft.Crosslight.Data;
using Intersoft.Crosslight.Data.ComponentModel;
using Intersoft.Crosslight.Data.EntityModel;
using System.ComponentModel;
namespace ViewProjectionSample.DomainModels
{
    
    public partial interface IAddressRepository : IEditableEntityRepository<Address, int>
	{
	}

	public partial class AddressRepository : EditableEntityRepository<Address, int>, IAddressRepository
	{
		public AddressRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "Addresses";
		}
	}

    public partial interface ICustomerRepository : IEditableEntityRepository<Customer, int>
	{
	}

	public partial class CustomerRepository : EditableEntityRepository<Customer, int>, ICustomerRepository
	{
		public CustomerRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "Customers";
		}
	}

    public partial interface ICustomerAddressRepository : IEditableEntityRepository<CustomerAddress>
	{
	}

	public partial class CustomerAddressRepository : EditableEntityRepository<CustomerAddress>, ICustomerAddressRepository
	{
		public CustomerAddressRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "CustomerAddresses";
		}
	}

    public partial interface IProductRepository : IEditableEntityRepository<Product, int>
	{
	}

	public partial class ProductRepository : EditableEntityRepository<Product, int>, IProductRepository
	{
		public ProductRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "Products";
		}
	}

    public partial interface IProductCategoryRepository : IEditableEntityRepository<ProductCategory, int>
	{
	}

	public partial class ProductCategoryRepository : EditableEntityRepository<ProductCategory, int>, IProductCategoryRepository
	{
		public ProductCategoryRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "ProductCategories";
		}
	}

    public partial interface IProductDescriptionRepository : IEditableEntityRepository<ProductDescription, int>
	{
	}

	public partial class ProductDescriptionRepository : EditableEntityRepository<ProductDescription, int>, IProductDescriptionRepository
	{
		public ProductDescriptionRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "ProductDescriptions";
		}
	}

    public partial interface IProductModelRepository : IEditableEntityRepository<ProductModel, int>
	{
	}

	public partial class ProductModelRepository : EditableEntityRepository<ProductModel, int>, IProductModelRepository
	{
		public ProductModelRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "ProductModels";
		}
	}

    public partial interface IProductModelProductDescriptionRepository : IEditableEntityRepository<ProductModelProductDescription>
	{
	}

	public partial class ProductModelProductDescriptionRepository : EditableEntityRepository<ProductModelProductDescription>, IProductModelProductDescriptionRepository
	{
		public ProductModelProductDescriptionRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "ProductModelProductDescriptions";
		}
	}

    public partial interface ISalesOrderDetailRepository : IEditableEntityRepository<SalesOrderDetail>
	{
	}

	public partial class SalesOrderDetailRepository : EditableEntityRepository<SalesOrderDetail>, ISalesOrderDetailRepository
	{
		public SalesOrderDetailRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "SalesOrderDetails";
		}
	}

    public partial interface ISalesOrderHeaderRepository : IEditableEntityRepository<SalesOrderHeader, int>
	{
	}

	public partial class SalesOrderHeaderRepository : EditableEntityRepository<SalesOrderHeader, int>, ISalesOrderHeaderRepository
	{
		public SalesOrderHeaderRepository(IEntityContainer entityContainer) : base(entityContainer)
		{
			this.ResourceName = "SalesOrderHeaders";
		}
	}

}
