




//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyInventory.DomainModels.Controllers
{
    using Intersoft.Data.WebApi;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Linq;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.OData.Query;
    using MyInventory.DomainModels;
    
    [EntityController(AllowMultipartMedia = true)]
    public partial class InventoryController : ApiController
    {
        private EntityContextProvider<InventoryEntities> db = new EntityContextProvider<InventoryEntities>();
        
        [HttpGet]
		public QueryResult Categories(ODataQueryOptions<Category> options)
		{
			return this.ToQueryResult<Category>(db.Context.Categories, options);
		}

        [HttpGet]
		public QueryResult Items(ODataQueryOptions<Item> options)
		{
			return this.ToQueryResult<Item>(db.Context.Items, options);
		}

        [HttpPost]
        public SaveResult SaveChanges(MultipartData saveBundle)
        {
            return db.SaveChanges(saveBundle);
        }
    }
}

